mdl = gcs;
load 'synthData_spesession';
numExp = length(SDOSessionData.Data.ToolData.ParameterEstimation.LocalExperiments);
% numTau = 3; % number of time constants
% estimExp = 1; % 1: 20C, 2: 5C, 3: 40C
prm_dyn = num2str(numTau+1);
set_param([mdl '/battery'],'prm_dyn',prm_dyn)
set_param([mdl '/battery'],'V0_vec_conf','runtime');
set_param([mdl '/battery'],'R0_vec_conf','runtime');

SDOSessionData.Data.Workspace. ...
    HiddenWorkspace.EstimatedParams(1,1) = param.Continuous('Em', Em);
SDOSessionData.Data.Workspace. ...
    HiddenWorkspace.EstimatedParams(1,1).Minimum = Em_min;
SDOSessionData.Data.Workspace. ...
    HiddenWorkspace.EstimatedParams(1,1).Maximum = Em_max;

SDOSessionData.Data.Workspace. ...
   HiddenWorkspace.EstimatedParams(2,1) = param.Continuous('R0', R0);
SDOSessionData.Data.Workspace. ...
    HiddenWorkspace.EstimatedParams(2,1).Minimum = R0_min;
SDOSessionData.Data.Workspace. ...
    HiddenWorkspace.EstimatedParams(2,1).Maximum = R0_max;

for i = 1 : numTau
    set_param([mdl '/battery'],['R' num2str(i) '_vec'],['R' num2str(i)]);
    set_param([mdl '/battery'],['tau' num2str(i) '_vec'],['tau' num2str(i)]);
    set_param([mdl '/battery'],['R' num2str(i) '_vec_conf'],'runtime');
    set_param([mdl '/battery'],['tau' num2str(i) '_vec_conf'],'runtime');
    
    % placeholder
    SDOSessionData.Data.Workspace. ...
        HiddenWorkspace.EstimatedParams(2+2*i-1,1) = ...
        param.Continuous("R"+i, evalin('base',"R"+i));
    SDOSessionData.Data.Workspace. ...
        HiddenWorkspace.EstimatedParams(2+2*i,1) = ...
        param.Continuous("tau" + i, evalin('base', "tau"+i));
    
    SDOSessionData.Data.Workspace. ...
        HiddenWorkspace.EstimatedParams(2+2*i-1,1).Value = evalin('base',['R' num2str(i)]);
    SDOSessionData.Data.Workspace. ...
        HiddenWorkspace.EstimatedParams(2+2*i-1,1).Minimum = evalin('base',['R' num2str(i) '_min']);
    SDOSessionData.Data.Workspace. ...
        HiddenWorkspace.EstimatedParams(2+2*i-1,1).Maximum = evalin('base',['R' num2str(i) '_max']);
    SDOSessionData.Data.Workspace. ...
        HiddenWorkspace.EstimatedParams(2+2*i-1,1).Scale = evalin('base',['R' num2str(i)]);
    SDOSessionData.Data.Workspace. ...
        HiddenWorkspace.EstimatedParams(2+2*i,1).Value = evalin('base',['tau' num2str(i)]);
    SDOSessionData.Data.Workspace. ...
        HiddenWorkspace.EstimatedParams(2+2*i,1).Minimum = evalin('base',['tau' num2str(i) '_min']);
    SDOSessionData.Data.Workspace. ...
        HiddenWorkspace.EstimatedParams(2+2*i,1).Maximum = evalin('base',['tau' num2str(i) '_max']);
    SDOSessionData.Data.Workspace. ...
        HiddenWorkspace.EstimatedParams(2+2*i,1).Scale = evalin('base',['tau' num2str(i)]);
end

%%
for i=1:numExp
    SDOSessionData.Data.ToolData.ParameterEstimation.LocalExperiments(i). ...
        SelectedForEstimation = false;
end
SDOSessionData.Data.ToolData.ParameterEstimation.LocalExperiments(estimExp). ...
    SelectedForEstimation = true;
SDOSessionData.Data.ToolData.PlotManager.Plots(1).Sources = ...
    {SDOSessionData.Data.ToolData.ParameterEstimation.LocalExperiments(estimExp). ...
    Experiment};
set_param('batteryParameterEstimation','FastRestart','on')

%%
spetool(SDOSessionData)
save_system